mysql paas/paas backup: note `mysqldump` flags that might be needed on newer versions
alphagov/paas-tech-docs pull request #453
Opened 2022-06-21 16:06 UTC by risicle

What
----

See https://govuk.zendesk.com/agent/tickets/5000660

Figuring out the exact combinations of server/client versions that need these and communicating that here would be too much. This at least points people in the right direction.

![Screenshot_20220621_170733](https://user-images.githubusercontent.com/807447/174846545-cc0d638c-4d24-4664-a0a9-78c42fa6396c.png)

How to review
-------------

Describe the steps required to test the changes.

1. Preview the content locally ([see README](https://github.com/alphagov/paas-tech-docs#preview)) and check that it renders as expected.
1. Manually check that any removed or renamed anchor tags are not in use ([linkchecker](https://github.com/linkcheck/linkchecker) doesn't do this).
1. …

Who can review
--------------

Not @risicle

2022-06-24 08:24 UTC, schmie requested changes
Hello and apologies this collides with Cat's as well - I did not realise I had left the review in a pending state 🙄

2022-06-27 08:45 UTC, risicle commented
Markdown parser really really doesn't like list items beginning with `--`

2022-06-27 10:55 UTC, schmie commented on source/documentation/deploying_services/mysql.md
> +    Depending on the version of your local `mysqldump` tool you may need to provide it with the additional flags `--no-tablespaces` and/or `--column-statistics=0`.
Taken into account by latest iteration modulo some changes due to rendering restrictions

2022-06-27 10:55 UTC, schmie approved these changes

2022-06-27 15:39 UTC, merged