[#183047939] Add maintenance window retrieval info for redis
alphagov/paas-tech-docs pull request #458
Opened 2022-09-13 10:02 UTC by whi-tw

## What

Add info for how to retrieve the maintenance windows for redis service instances.

## How to review

Describe the steps required to test the changes.

1. Preview the content locally ([see README](https://github.com/alphagov/paas-tech-docs#preview)) and check that it renders as expected.
1. Manually check that any removed or renamed anchor tags are not in use ([linkchecker](https://github.com/linkcheck/linkchecker) doesn't do this).
1. Check the content is correct

## Who can review

Not me

2022-09-16 14:26 UTC, cadmiumcat commented on source/documentation/deploying_services/redis.md.erb
> +
```suggestion
Here is an example of the output you will see:
```

2022-09-16 14:27 UTC, cadmiumcat reviewed
Looks good 👍. I've added a suggestion
Do we need a tech writer to double check this?

2022-09-21 10:55 UTC, cadmiumcat approved these changes
Very minor change from tech writer. Good otherwise! 👍

2022-11-07 10:54 UTC, risicle commented
(otherwise I'd like to copy this block to the postgres section)

2022-11-10 09:45 UTC, risicle approved these changes
*I* like this, should probably double check with a tech writer.

2022-11-10 10:17 UTC, cmcnallygds commented on source/documentation/deploying_services/redis.md.erb
> +Every Redis service instance has a maintenance window pre-configured. The day and time of this maintenance window can be retrieved with the Cloud Foundry CLI (version 8 and above) by running:
```suggestion
Every Redis service instance has a maintenance window pre-configured. You can retrieve the day and time of this maintenance window with the Cloud Foundry CLI (version 8 and above) by running:
```

2022-11-10 10:19 UTC, cmcnallygds requested changes
Looks good - have suggested a small change to get rid of passive voice as per the style guide.

2022-11-10 10:52 UTC, cmcnallygds approved these changes

2022-11-10 11:07 UTC, merged