route_services: add caveat about using ip-restriction service with CDNs
alphagov/paas-tech-docs pull request #476
Opened 2023-01-04 17:11 UTC by risicle

What
----

https://www.pivotaltracker.com/story/show/180890489

Thinking about this more, if we were in other circumstances the thing to do here would probably be to just add a script to the `paas-ip-authentication-route-service` repo that would scrape and insert/update the appropriate IPs for them.

How to review
-------------

Describe the steps required to test the changes.

1. Preview the content locally ([see README](https://github.com/alphagov/paas-tech-docs#preview)) and check that it renders as expected.
1. Manually check that any removed or renamed anchor tags are not in use ([linkchecker](https://github.com/linkcheck/linkchecker) doesn't do this).
1. …

2023-01-04 18:03 UTC, cmcnallygds commented on source/documentation/deploying_services/route_services.md
> +when used with requests routed via a CDN. This includes requests routed via our
```suggestion
when used with requests routed through a CDN. This includes requests routed through our
```

2023-01-04 18:04 UTC, cmcnallygds commented on source/documentation/deploying_services/route_services.md
> +entries need to be added to `nginx.conf` for all IP-ranges the CDN may forward
```suggestion
entries need to be added to `nginx.conf` for all IP ranges the CDN may forward
```

2023-01-04 18:05 UTC, cmcnallygds commented on source/documentation/deploying_services/route_services.md
> +via a JSON file. These ranges are not completely static and will need to be
```suggestion
via a JSON file. These ranges are not completely static and you will need to 
```

2023-01-04 18:05 UTC, cmcnallygds commented on source/documentation/deploying_services/route_services.md
> +updated occasionally.
```suggestion
update them occasionally.
```

2023-01-04 18:06 UTC, cmcnallygds requested changes
Requesting some style changes so content is line with style guide

2023-01-05 10:43 UTC, risicle commented
My beautiful hyphens!

2023-01-05 11:48 UTC, cmcnallygds commented on source/documentation/deploying_services/route_services.md
> +own AWS CloudFront-based [cdn-route services](/deploying_services/use_a_custom_domain/). For these to work, [`set_real_ip_from`](https://nginx.org/en/docs/http/ngx_http_realip_module.html#set_real_ip
```suggestion
own AWS CloudFront-based [cdn-route services](/deploying_services/use_a_custom_domain/). For these to work, you need to add [`set_real_ip_from`](https://nginx.org/en/docs/http/ngx_http_realip_module.html#set_real_ip_from)
```

2023-01-05 11:49 UTC, cmcnallygds commented on source/documentation/deploying_services/route_services.md
> +entries need to be added to `nginx.conf` for all IP ranges the CDN may forward
```suggestion
entries to `nginx.conf` for all IP ranges the CDN may forward
```

2023-01-05 11:50 UTC, cmcnallygds commented on source/documentation/deploying_services/route_services.md
> +entries need to be added to `nginx.conf` for all IP ranges the CDN may forward
Could we avoid the passive voice here by asking the user directly to carry out this action?

2023-01-05 11:51 UTC, cmcnallygds requested changes
Suggesting the use of active voice rather than passive

2023-01-05 12:05 UTC, risicle commented
All sounds very dictatorial to me but if it's the style guide...

2023-01-05 13:52 UTC, cmcnallygds approved these changes

2023-01-05 14:02 UTC, cadmiumcat approved these changes

2023-01-05 14:28 UTC, merged