Add a note about not relying on `cf logs`
alphagov/paas-tech-docs pull request #488
Opened 2023-02-10 10:55 UTC by AP-Hunt

What
----

There are lots of different ways `cf logs` can give you a suboptimal experience. You should use a syslog drain for stuff you really care about.

How to review
-------------

1. Accurate copy?
2. Correct tone?

Who can review
--------------

Describe who can review the changes. Or more importantly, list the people
that can't review, because they worked on it.

2023-02-10 11:06 UTC, corlettb commented
Should we link to the reliability section for log-cache?

https://github.com/cloudfoundry/log-cache-release#reliability

2023-02-10 11:11 UTC, risicle commented on source/documentation/monitoring_apps/logs.md
> +own log storage.
```suggestion
own log storage system.
```

Less misunderstandable as something possible in-cloudfoundry?

2023-02-13 10:46 UTC, AP-Hunt commented
Good shout @corlettb

2023-02-13 12:49 UTC, corlettb approved these changes
LGTM

2023-02-13 14:06 UTC, cmcnallygds commented on source/documentation/monitoring_apps/logs.md
> +through `cf logs`](https://github.com/cloudfoundry/log-cache-release#reliability). You should not rely solely on it for your production
```suggestion
through `cf logs`](https://github.com/cloudfoundry/log-cache-release#reliability). You should not rely solely on `cf logs` for your production
```

2023-02-13 14:07 UTC, cmcnallygds requested changes
Small suggestion for clarity

2023-02-15 16:36 UTC, cmcnallygds approved these changes

2023-02-15 16:41 UTC, closed without merging